### ISSUE TITLE
PSR 16 Support

### ISSUE THREAD

**Issue by Nilithus** [QuickenLoans/mcp-cache#1]
In the readme:

> This package has many similarities with the draft PSR-16 Simple Cache. If this PSR is accepted, we will update this package to ensure compatibility.

[PSR 16](http://www.php-fig.org/psr/psr-16/) has been officially accepted.

**Comment by Nilithus** [comment]
The `PSR16CacheInterface::clean()` method seems very dangerous in the case of`Predis` since there is no really good way to delete keys matching a pattern without writing a pretty poor performing lua script. Must implementations use `$predis->flushAll()` or `$predis->flushDb` but I know many redis instances are shared with cache and session data and generally don't do a good job of keeping them in separate redis databases and rely on key prefixes.

You could say people should know what is happening when they call `$cache->clean` but depending on which implementation you use one could just clear an array as `MemoryCache` does and one might sign out every user on your site (or any application sharing your redis instance) if you haven't configured redis to store session and cache in different databases.

**Comment by skluck** [comment]
Session data semantically isn't cached data. But if the underlying redis (or whatever) store is wiped by a psr-12 cacher and that store also contains non-cache data... well I don't think its a situation worth worrying about. 

I am not so sure the implementation needs to worry about flushing the entire store. Clear could merely change some prefix hash key. That does require it to be stateful and not static though (e.g. storing it in the backend store itself rather than static configuration).
